Adding items needed for GitPod
FusionAuth/fusionauth-example-express-start-here pull request #2
Opened 2024-12-30 22:01 UTC by synedra

Items for gitpod:
* Changed the docker-compose to eliminate search (as it was making the process very slow)
* Created a GITPOD.md with in-IDE instructions for people to follow there, comes up as soon as the env starts
* Added information about Delegate here (echoing what's on the website) since GitPod is so all-encompassing it seemed to make sense for the flow.
* GitPod changes can be tested with the GitPod button

2025-01-06 23:39 UTC, mooreds requested changes
A few changes.

2025-01-06 23:39 UTC, mooreds commented on GITPOD.md
> +The next step is to delegate authentication for your application, and verify that the change is applied.  For this you will:
Are these instructions still correct? Do we need to keep them in sync with the instructions in fusionauth-site or can we just point people to the 'get started' section in the techdocs?

2025-01-06 23:39 UTC, mooreds commented on README.md
> +[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/#https://github.com/synedra/fusionauth-example-express-start-here)
do you need to update that repo which points to synedra?

2025-01-06 23:39 UTC, mooreds commented on app/src/index.ts
> +#tag::validateUser[]
Is a `#` a validate comment marker? I thought for JS you were supposed to use `//`?

2025-01-06 23:39 UTC, mooreds commented on docker-compose.yml
> -      SEARCH_TYPE: elasticsearch
You need to set the `SEARCH_TYPE` to `database`, I believe. Looks like the default is `database` but better to be explicit.

2025-01-06 23:39 UTC, mooreds commented on ports.sh
> +
Please add a comment explaining what this script is doing.

2025-01-07 01:04 UTC, synedra commented on GITPOD.md
> +The next step is to delegate authentication for your application, and verify that the change is applied.  For this you will:
Let's go over this when we review.  Because they get put *into* the environment, I'm a little wary of having them go out of the environment to read more instructions (because they might lose the tab or whatever).  I should be able to load the instructions from -site and maybe that's the right plan.

2025-01-07 01:04 UTC, synedra commented on README.md
> +[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/#https://github.com/synedra/fusionauth-example-express-start-here)
I will, when the fusionauth repo is updated :-)

2025-01-07 01:05 UTC, synedra commented on app/src/index.ts
> +#tag::validateUser[]
I should just take that out in any case, we're going through things in a much better way with your tagged sections.

2025-01-07 01:15 UTC, synedra commented on GITPOD.md
> +The next step is to delegate authentication for your application, and verify that the change is applied.  For this you will:
So I think the right answer is to point them to an anchored part of the guide on -site, which we can open into a window in the environment.  I'll need to make sure the experience flows well.  I can't currently do this because I think the *right* thing is to point to a page on fusionauth.io, not GitHub, and the start-here isn't pushed yet.  Does that make sense?

2025-01-07 16:56 UTC, mooreds commented on GITPOD.md
> +The next step is to delegate authentication for your application, and verify that the change is applied.  For this you will:
Makes sense. I get that this is a work in progress and that moving between two repos, one of which is not on main or published, makes things a bit tricky.

2025-01-07 16:56 UTC, mooreds approved these changes, later dismissed

2025-01-08 18:18 UTC, mooreds commented
Will approve this whenever you are done making changes, just let me know.

2025-01-15 18:24 UTC, mooreds approved these changes
LGTM

2025-01-15 18:43 UTC, merged